language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local-dir: ./build/
  github-token: $GITHUB_TOKEN
  keep-history: true
  name: Deployment Bot
  email: deploy@travis-ci.org
on:
  branch: master
  
